/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnicalIndexRouteImport } from './routes/technical/index'
import { Route as NocIndexRouteImport } from './routes/noc/index'
import { Route as HelpdeskIndexRouteImport } from './routes/helpdesk/index'
import { Route as TrackerIdRouteImport } from './routes/tracker/$id'
import { Route as NocTechniciansRouteImport } from './routes/noc/technicians'
import { Route as HelpdeskCreateRouteImport } from './routes/helpdesk/create'
import { Route as HelpdeskMonitoringIndexRouteImport } from './routes/helpdesk/monitoring.index'
import { Route as TechnicalAssignmentsIdRouteImport } from './routes/technical/assignments.$id'
import { Route as NocTicketsIdRouteImport } from './routes/noc/tickets.$id'
import { Route as HelpdeskMonitoringIdRouteImport } from './routes/helpdesk/monitoring.$id'
import { Route as HelpdeskEditIdRouteImport } from './routes/helpdesk/edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalIndexRoute = TechnicalIndexRouteImport.update({
  id: '/technical/',
  path: '/technical/',
  getParentRoute: () => rootRouteImport,
} as any)
const NocIndexRoute = NocIndexRouteImport.update({
  id: '/noc/',
  path: '/noc/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskIndexRoute = HelpdeskIndexRouteImport.update({
  id: '/helpdesk/',
  path: '/helpdesk/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerIdRoute = TrackerIdRouteImport.update({
  id: '/tracker/$id',
  path: '/tracker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NocTechniciansRoute = NocTechniciansRouteImport.update({
  id: '/noc/technicians',
  path: '/noc/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskCreateRoute = HelpdeskCreateRouteImport.update({
  id: '/helpdesk/create',
  path: '/helpdesk/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskMonitoringIndexRoute = HelpdeskMonitoringIndexRouteImport.update({
  id: '/helpdesk/monitoring/',
  path: '/helpdesk/monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalAssignmentsIdRoute = TechnicalAssignmentsIdRouteImport.update({
  id: '/technical/assignments/$id',
  path: '/technical/assignments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NocTicketsIdRoute = NocTicketsIdRouteImport.update({
  id: '/noc/tickets/$id',
  path: '/noc/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskMonitoringIdRoute = HelpdeskMonitoringIdRouteImport.update({
  id: '/helpdesk/monitoring/$id',
  path: '/helpdesk/monitoring/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskEditIdRoute = HelpdeskEditIdRouteImport.update({
  id: '/helpdesk/edit/$id',
  path: '/helpdesk/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/helpdesk/create': typeof HelpdeskCreateRoute
  '/noc/technicians': typeof NocTechniciansRoute
  '/tracker/$id': typeof TrackerIdRoute
  '/helpdesk/': typeof HelpdeskIndexRoute
  '/noc/': typeof NocIndexRoute
  '/technical/': typeof TechnicalIndexRoute
  '/helpdesk/edit/$id': typeof HelpdeskEditIdRoute
  '/helpdesk/monitoring/$id': typeof HelpdeskMonitoringIdRoute
  '/noc/tickets/$id': typeof NocTicketsIdRoute
  '/technical/assignments/$id': typeof TechnicalAssignmentsIdRoute
  '/helpdesk/monitoring/': typeof HelpdeskMonitoringIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/helpdesk/create': typeof HelpdeskCreateRoute
  '/noc/technicians': typeof NocTechniciansRoute
  '/tracker/$id': typeof TrackerIdRoute
  '/helpdesk': typeof HelpdeskIndexRoute
  '/noc': typeof NocIndexRoute
  '/technical': typeof TechnicalIndexRoute
  '/helpdesk/edit/$id': typeof HelpdeskEditIdRoute
  '/helpdesk/monitoring/$id': typeof HelpdeskMonitoringIdRoute
  '/noc/tickets/$id': typeof NocTicketsIdRoute
  '/technical/assignments/$id': typeof TechnicalAssignmentsIdRoute
  '/helpdesk/monitoring': typeof HelpdeskMonitoringIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/helpdesk/create': typeof HelpdeskCreateRoute
  '/noc/technicians': typeof NocTechniciansRoute
  '/tracker/$id': typeof TrackerIdRoute
  '/helpdesk/': typeof HelpdeskIndexRoute
  '/noc/': typeof NocIndexRoute
  '/technical/': typeof TechnicalIndexRoute
  '/helpdesk/edit/$id': typeof HelpdeskEditIdRoute
  '/helpdesk/monitoring/$id': typeof HelpdeskMonitoringIdRoute
  '/noc/tickets/$id': typeof NocTicketsIdRoute
  '/technical/assignments/$id': typeof TechnicalAssignmentsIdRoute
  '/helpdesk/monitoring/': typeof HelpdeskMonitoringIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/helpdesk/create'
    | '/noc/technicians'
    | '/tracker/$id'
    | '/helpdesk/'
    | '/noc/'
    | '/technical/'
    | '/helpdesk/edit/$id'
    | '/helpdesk/monitoring/$id'
    | '/noc/tickets/$id'
    | '/technical/assignments/$id'
    | '/helpdesk/monitoring/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/helpdesk/create'
    | '/noc/technicians'
    | '/tracker/$id'
    | '/helpdesk'
    | '/noc'
    | '/technical'
    | '/helpdesk/edit/$id'
    | '/helpdesk/monitoring/$id'
    | '/noc/tickets/$id'
    | '/technical/assignments/$id'
    | '/helpdesk/monitoring'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/helpdesk/create'
    | '/noc/technicians'
    | '/tracker/$id'
    | '/helpdesk/'
    | '/noc/'
    | '/technical/'
    | '/helpdesk/edit/$id'
    | '/helpdesk/monitoring/$id'
    | '/noc/tickets/$id'
    | '/technical/assignments/$id'
    | '/helpdesk/monitoring/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  HelpdeskCreateRoute: typeof HelpdeskCreateRoute
  NocTechniciansRoute: typeof NocTechniciansRoute
  TrackerIdRoute: typeof TrackerIdRoute
  HelpdeskIndexRoute: typeof HelpdeskIndexRoute
  NocIndexRoute: typeof NocIndexRoute
  TechnicalIndexRoute: typeof TechnicalIndexRoute
  HelpdeskEditIdRoute: typeof HelpdeskEditIdRoute
  HelpdeskMonitoringIdRoute: typeof HelpdeskMonitoringIdRoute
  NocTicketsIdRoute: typeof NocTicketsIdRoute
  TechnicalAssignmentsIdRoute: typeof TechnicalAssignmentsIdRoute
  HelpdeskMonitoringIndexRoute: typeof HelpdeskMonitoringIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/': {
      id: '/technical/'
      path: '/technical'
      fullPath: '/technical/'
      preLoaderRoute: typeof TechnicalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noc/': {
      id: '/noc/'
      path: '/noc'
      fullPath: '/noc/'
      preLoaderRoute: typeof NocIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk/': {
      id: '/helpdesk/'
      path: '/helpdesk'
      fullPath: '/helpdesk/'
      preLoaderRoute: typeof HelpdeskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/$id': {
      id: '/tracker/$id'
      path: '/tracker/$id'
      fullPath: '/tracker/$id'
      preLoaderRoute: typeof TrackerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noc/technicians': {
      id: '/noc/technicians'
      path: '/noc/technicians'
      fullPath: '/noc/technicians'
      preLoaderRoute: typeof NocTechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk/create': {
      id: '/helpdesk/create'
      path: '/helpdesk/create'
      fullPath: '/helpdesk/create'
      preLoaderRoute: typeof HelpdeskCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk/monitoring/': {
      id: '/helpdesk/monitoring/'
      path: '/helpdesk/monitoring'
      fullPath: '/helpdesk/monitoring/'
      preLoaderRoute: typeof HelpdeskMonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/assignments/$id': {
      id: '/technical/assignments/$id'
      path: '/technical/assignments/$id'
      fullPath: '/technical/assignments/$id'
      preLoaderRoute: typeof TechnicalAssignmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noc/tickets/$id': {
      id: '/noc/tickets/$id'
      path: '/noc/tickets/$id'
      fullPath: '/noc/tickets/$id'
      preLoaderRoute: typeof NocTicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk/monitoring/$id': {
      id: '/helpdesk/monitoring/$id'
      path: '/helpdesk/monitoring/$id'
      fullPath: '/helpdesk/monitoring/$id'
      preLoaderRoute: typeof HelpdeskMonitoringIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk/edit/$id': {
      id: '/helpdesk/edit/$id'
      path: '/helpdesk/edit/$id'
      fullPath: '/helpdesk/edit/$id'
      preLoaderRoute: typeof HelpdeskEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  HelpdeskCreateRoute: HelpdeskCreateRoute,
  NocTechniciansRoute: NocTechniciansRoute,
  TrackerIdRoute: TrackerIdRoute,
  HelpdeskIndexRoute: HelpdeskIndexRoute,
  NocIndexRoute: NocIndexRoute,
  TechnicalIndexRoute: TechnicalIndexRoute,
  HelpdeskEditIdRoute: HelpdeskEditIdRoute,
  HelpdeskMonitoringIdRoute: HelpdeskMonitoringIdRoute,
  NocTicketsIdRoute: NocTicketsIdRoute,
  TechnicalAssignmentsIdRoute: TechnicalAssignmentsIdRoute,
  HelpdeskMonitoringIndexRoute: HelpdeskMonitoringIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
